on:
  workflow_call:
    inputs:

## this would be nice
# defaults:
#   run:
#     shell: bash
#     working-directory: ./frontend

inputs:
  version:
    description: 'current version to be added to env (and shown in app)'
    required: false
    default: 'noversion'

runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v2
      with:
        java-version: '17.x'
        distribution: 'temurin'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.10.1'
        channel: 'stable'
        cache: true
    - run: |
        cd frontend/
        touch .env
        echo "API_KEY=$API_KEY" >> .env
        echo "API_URL=$API_URL" >> .env
        echo "VERSION=${{ inputs.version}}" >> .env
      shell: bash
    - name: install dependencies and run code gen
      run: |
        cd frontend/
        flutter pub get #make sure this path is correct
        dart run build_runner build --delete-conflicting-outputs
      shell: bash

