version: '3' 
services:
  node-api-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
          CERT_PATH: ${CERT_PATH}
    ports:
      - "443:443"
    volumes:
      - "/etc/letsencrypt"
