version: '3' 
services:
  node-api-server:
    user: "${UID}:${GID}"
    restart: always
    image: node:17-alpine
    working_dir: /home/node/api
 # das ist etwas whack, idealerweise würde der postgres-service ebenfalls dockerized sein dann wär das nicht nötig
    network_mode: host
 #   ports:
 #     - "443:443"
 #     - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /home/administrator/images:/home/administrator/images
      - ${CERT_PATH}:${CERT_PATH}

      - .:/home/node/api
    command: sh -c "
        npm install --quiet 
        && node --unhandled-rejections=warn index.js
      "

