name: test flutter application (unit / widget / integration)
on: 
  pull_request:
  push: 
    branches:
      - main
      - release
      - 'releases/**'
      - '!releases/**-alpha'

jobs:
  run:
    name: test
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.API_KEY}}
      API_URL: https://inspection.mbg-solutions.com/api/secure #edit this if necessary
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.x'
      - run: |
          touch .env
          echo "API_KEY=$API_KEY" >> .env
          echo "\n" >> .env
          echo "API_URL=$API_URL" >> .env
      - name: install dependencies
        run: flutter pub get
      - name: run tests and report coverage
        run: flutter test --coverage
      - name: comment coverage
        if: github.event.pull_request
        uses: romeovs/lcov-reporter-action@v0.2.16 
        with:
          github-token: ${{secrets.TOKEN_GITHUB}} #todo
