name: Create Documentation and Publish to gh-pages
on: 
  push:
    branches:
      - main
      - release
      - 'releases/**'
      - '!releases/**-alpha'
jobs:
  build-and-deploy:
    env:
      API_KEY: "add web api key here" #${{ secrets.API_KEY}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd frontend
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.x'
      - run: |
          touch .env
          echo "API_KEY=$API_KEY" >> .env
      - name: install dependencies
        run: flutter pub get
      - name: Build Documentation
        run: |
          flutter pub global activate dartdoc
          flutter pub global run dartdoc
      - name: Build Web-App
        run: flutter build web

      - name: make gh-pages folder for doc as well as the app
        run: |
          mkdir gh-pages
          mv doc/api gh-pages/doc
          mv build/web gh-pages/app
          cd gh-pages && touch .nojekyll 
        # the last command is needed to serve the .env

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: frontend/gh-pages # The folder the action should deploy, created in prev. step
